language: go
go:
    - 1.11.x

os:
    - linux

dist: xenial

before_install:
    - sudo apt-get install -y libasound2-dev

env:
    - GO111MODULE=on

install: true

jobs:
    include:
        deploy:
            provider: releases
            api_key: $GITHUB_OAUTH_TOKEN
            file: podman
            skip_cleanup: true
            on:
                tags: true
